import React, { useEffect, useState, useMemo } from 'react';
import { useTranslation } from 'react-i18next';
import { motion, AnimatePresence } from 'framer-motion';

interface RunwaySession {
  id: number;
  product_id: number;
  product_name: string;
  status: string;
  current_step: number;
  auto_mode: boolean;
  threat_model: string | null;
  security_plan: string | null;
  remediation: string | null;
  poc: string | null;
  audit_report: string | null;
  scan_count_before: number;
  scan_count_after: number;
  error_message: string | null;
  created_at: string;
  updated_at: string;
}

const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: { staggerChildren: 0.05 }
  }
};

const itemVariants = {
  hidden: { opacity: 0, y: 12 },
  visible: {
    opacity: 1,
    y: 0,
    transition: { type: "spring" as const, stiffness: 260, damping: 25 }
  }
};

export const RunwayReportsPage: React.FC = () => {
  const { t } = useTranslation(['pages', 'components']);
  const [sessions, setSessions] = useState<RunwaySession[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [expandedId, setExpandedId] = useState<number | null>(null);
  const [exportingId, setExportingId] = useState<number | null>(null);
  const [previewTab, setPreviewTab] = useState<'threat' | 'plan' | 'remediation' | 'poc' | 'report'>('report');

  const fetchSessions = async () => {
    setLoading(true);
    try {
      const res = await fetch('/api/runway/all');
      const data = await res.json();
      if (data.ok) {
        setSessions(data.sessions || []);
      } else {
        setError(data.error || 'Failed to load runway reports.');
      }
    } catch (e) {
      setError('Failed to fetch runway reports history due to network error.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchSessions();
  }, []);

  const handleDownloadMarkdown = (sess: RunwaySession) => {
    let md = `# 🛡️ AITriage Security Audit Report\n\n`;
    md += `**Project**: ${sess.product_name || 'Unknown'}\n`;
    md += `**Date**: ${new Date(sess.created_at).toLocaleString()}\n`;
    md += `**Session ID**: ${sess.id}\n`;
    md += `**Status**: ${sess.status}\n`;
    md += `**Findings**: ${sess.scan_count_before} before → ${sess.scan_count_after} after\n\n`;
    md += `---\n\n`;

    if (sess.threat_model) {
      md += `## 1. STRIDE Threat Model\n\n${sess.threat_model}\n\n---\n\n`;
    }
    if (sess.security_plan) {
      md += `## 2. Security Implementation Plan\n\n${sess.security_plan}\n\n---\n\n`;
    }
    if (sess.remediation) {
      md += `## 3. Remediation Patches\n\n${sess.remediation}\n\n---\n\n`;
    }
    if (sess.poc) {
      md += `## 4. Proof of Concept Verification\n\n${sess.poc}\n\n---\n\n`;
    }
    if (sess.audit_report) {
      md += `## 5. Audit Report\n\n${sess.audit_report}\n\n---\n\n`;
    }
    md += `\n*Generated by AITriage SecureCoder Agent*\n`;

    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute("href", url);
    const dateStr = new Date(sess.created_at).toISOString().split('T')[0];
    downloadAnchor.setAttribute("download", `runway-report-${sess.id}-${dateStr}.md`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
    URL.revokeObjectURL(url);
  };

  const handleExportToProject = async (sess: RunwaySession) => {
    setExportingId(sess.id);
    try {
      const res = await fetch(`/api/runway/export/${sess.id}`, { method: 'POST' });
      const data = await res.json();
      if (data.ok) {
        alert(t('SimpleDashboardPage.runway.exportSuccess', { path: data.saved_to || 'aitriage/' }));
      } else {
        alert(data.error || 'Failed to export report.');
      }
    } catch (e) {
      alert('Error exporting report: network failure.');
    } finally {
      setExportingId(null);
    }
  };

  const counts = useMemo(() => {
    return {
      total: sessions.length,
      completed: sessions.filter(s => s.status === 'completed').length,
      inProgress: sessions.filter(s => s.status === 'in_progress').length,
      failed: sessions.filter(s => s.status === 'failed').length,
    };
  }, [sessions]);

  return (
    <div className="h-full overflow-y-auto" style={{ scrollbarWidth: 'thin', scrollbarColor: 'rgba(255,255,255,0.06) transparent' }}>
      <motion.div 
        variants={containerVariants}
        initial="hidden"
        animate="visible"
        className="max-w-5xl mx-auto px-8 py-8 space-y-6"
      >
        {/* Header */}
        <motion.div variants={itemVariants} className="flex items-center justify-between">
          <div>
            <h1 className="text-lg font-bold text-white uppercase tracking-wider flex items-center gap-2">
              <span className="material-symbols-outlined text-[20px] text-[var(--accent-color)]">description</span>
              {t('components:tab_reports')}
            </h1>
            <p className="text-[11px] text-[#71717a] mt-0.5">
              History of all Runway security agent audit runs and generated reports.
            </p>
          </div>
          <button 
            onClick={fetchSessions}
            className="px-3 py-1.5 rounded-md border border-[rgba(255,255,255,0.06)] hover:bg-[rgba(255,255,255,0.02)] text-[12px] text-[#a1a1aa] transition-colors flex items-center gap-1.5 cursor-pointer"
          >
            <span className="material-symbols-outlined text-[14px]">refresh</span>
            Refresh
          </button>
        </motion.div>

        {/* Summary stats */}
        <motion.div variants={itemVariants} className="grid grid-cols-4 gap-3">
          {[
            { label: 'Total Runs', value: counts.total, icon: 'history', color: '#a1a1aa' },
            { label: 'Completed', value: counts.completed, icon: 'check_circle', color: '#22c55e' },
            { label: 'In Progress', value: counts.inProgress, icon: 'sync', color: '#38bdf8' },
            { label: 'Failed', value: counts.failed, icon: 'error', color: '#ef4444' },
          ].map(c => (
            <div key={c.label} className="border border-[rgba(255,255,255,0.06)] rounded-lg p-4 bg-[rgba(255,255,255,0.01)]">
              <div className="flex items-center gap-2 mb-2">
                <span className="material-symbols-outlined text-[16px]" style={{ color: c.color }}>{c.icon}</span>
                <span className="text-[11px] text-[#52525b] uppercase tracking-wider font-medium">{c.label}</span>
              </div>
              <div className="text-2xl font-bold text-[#f4f4f5] tabular-nums">{c.value}</div>
            </div>
          ))}
        </motion.div>

        {/* Error state */}
        {error && (
          <motion.div variants={itemVariants} className="p-4 bg-[rgba(239,68,68,0.05)] border border-[rgba(239,68,68,0.15)] rounded-lg text-[12px] text-[#f87171]">
            {error}
          </motion.div>
        )}

        {/* List / Table */}
        {loading ? (
          <div className="py-16 text-center">
            <div className="w-6 h-6 border-2 border-[var(--accent-color)] border-t-transparent rounded-full animate-spin mx-auto mb-3" />
            <span className="text-[12px] text-[#71717a] font-mono uppercase">Loading history...</span>
          </div>
        ) : sessions.length === 0 ? (
          <div className="py-16 text-center border border-dashed border-[rgba(255,255,255,0.06)] rounded-lg bg-[rgba(255,255,255,0.01)]">
            <span className="material-symbols-outlined text-[48px] text-[#18181b] block mb-3">folder_open</span>
            <div className="text-[13px] text-[#71717a]">No Runway sessions found.</div>
            <div className="text-[11px] text-[#52525b] mt-1">Run a SecureCoder Agent Runway scan from the overview dashboard first.</div>
          </div>
        ) : (
          <motion.div variants={itemVariants} className="border border-[rgba(255,255,255,0.06)] rounded-lg overflow-hidden divide-y divide-[rgba(255,255,255,0.06)] bg-[rgba(255,255,255,0.01)]">
            {sessions.map((sess) => {
              const isExpanded = expandedId === sess.id;
              const date = new Date(sess.created_at).toLocaleDateString(undefined, {
                year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit'
              });

              return (
                <div key={sess.id} className="transition-colors hover:bg-[rgba(255,255,255,0.005)]">
                  <div className="px-5 py-4 flex items-center justify-between gap-4">
                    {/* Basic info */}
                    <div onClick={() => setExpandedId(isExpanded ? null : sess.id)} className="flex-1 min-w-0 cursor-pointer flex items-center gap-3">
                      <span className="material-symbols-outlined text-[18px] text-[#71717a]">
                        {sess.status === 'completed' ? 'check_circle' : sess.status === 'failed' ? 'error' : 'sync'}
                      </span>
                      <div className="min-w-0">
                        <div className="text-[13px] font-medium text-[#f4f4f5] flex items-center gap-2">
                          <span>{sess.product_name || 'Unknown Project'}</span>
                          <span className="text-[10px] text-[#52525b] font-mono bg-[rgba(255,255,255,0.03)] px-1 py-0.5 rounded border border-[rgba(255,255,255,0.04)]">
                            ID {sess.id}
                          </span>
                        </div>
                        <div className="flex items-center gap-3 mt-1 text-[11px] text-[#71717a]">
                          <span>{date}</span>
                          <span>·</span>
                          {sess.status === 'completed' ? (
                            <span className="text-[#22c55e]">
                              {sess.scan_count_before} before → {sess.scan_count_after} after
                            </span>
                          ) : (
                            <span className="text-[#a1a1aa]">
                              Step {sess.current_step}/7
                            </span>
                          )}
                        </div>
                      </div>
                    </div>

                    {/* Actions */}
                    <div className="flex items-center gap-2 shrink-0">
                      <button
                        onClick={() => setExpandedId(isExpanded ? null : sess.id)}
                        className={`px-2.5 py-1.5 rounded text-[11px] font-bold uppercase tracking-wider transition-colors flex items-center gap-1 cursor-pointer ${
                          isExpanded
                            ? 'bg-[rgba(255,255,255,0.06)] text-[#f4f4f5]'
                            : 'hover:bg-[rgba(255,255,255,0.02)] text-[#a1a1aa]'
                        }`}
                      >
                        <span className="material-symbols-outlined text-[13px]">visibility</span>
                        Preview
                      </button>

                      <button
                        onClick={() => handleExportToProject(sess)}
                        disabled={exportingId === sess.id || sess.status !== 'completed'}
                        className="px-2.5 py-1.5 hover:bg-[rgba(255,255,255,0.02)] text-[#a1a1aa] rounded text-[11px] font-bold uppercase tracking-wider transition-colors flex items-center gap-1 cursor-pointer disabled:opacity-30 disabled:pointer-events-none"
                        title="Export markdown report directly to project's aitriage/ directory"
                      >
                        <span className="material-symbols-outlined text-[13px]">ios_share</span>
                        Export
                      </button>

                      <button
                        onClick={() => handleDownloadMarkdown(sess)}
                        disabled={sess.status !== 'completed'}
                        className="px-2.5 py-1.5 hover:bg-[rgba(255,255,255,0.02)] text-[#a1a1aa] rounded text-[11px] font-bold uppercase tracking-wider transition-colors flex items-center gap-1 cursor-pointer disabled:opacity-30 disabled:pointer-events-none"
                      >
                        <span className="material-symbols-outlined text-[13px]">download</span>
                        MD
                      </button>
                    </div>
                  </div>

                  {/* Expandable preview */}
                  <AnimatePresence initial={false}>
                    {isExpanded && (
                      <motion.div
                        key="preview"
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: "auto", opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        transition={{ type: "spring", stiffness: 300, damping: 30 }}
                        className="overflow-hidden border-t border-[rgba(255,255,255,0.04)] bg-[rgba(255,255,255,0.005)]"
                      >
                        <div className="px-5 py-4 space-y-4">
                          {/* Inner Tabs */}
                          <div className="flex items-center gap-1 border-b border-[rgba(255,255,255,0.04)] pb-2">
                            {[
                              { id: 'threat' as const, label: 'Threat Model', data: sess.threat_model },
                              { id: 'plan' as const, label: 'Security Plan', data: sess.security_plan },
                              { id: 'remediation' as const, label: 'Remediation', data: sess.remediation },
                              { id: 'poc' as const, label: 'Verification (PoC)', data: sess.poc },
                              { id: 'report' as const, label: 'Audit Report', data: sess.audit_report },
                            ].map((tab) => (
                              <button
                                key={tab.id}
                                disabled={!tab.data}
                                onClick={() => setPreviewTab(tab.id)}
                                className={`px-3 py-1.5 rounded text-[11px] font-medium transition-all ${
                                  previewTab === tab.id
                                    ? 'bg-[var(--accent-color)] text-[var(--accent-color-on-text)] font-semibold'
                                    : tab.data
                                    ? 'text-[#71717a] hover:text-[#a1a1aa]'
                                    : 'text-[#27272a] cursor-not-allowed'
                                }`}
                              >
                                {tab.label}
                              </button>
                            ))}
                          </div>

                          {/* Tab Content Display */}
                          <div className="bg-[#09090b] border border-[rgba(255,255,255,0.04)] rounded-lg p-5 overflow-x-auto max-h-96 overflow-y-auto">
                            {previewTab === 'threat' && sess.threat_model && (
                              <pre className="text-[12px] text-[#a1a1aa] font-mono leading-relaxed whitespace-pre-wrap">{sess.threat_model}</pre>
                            )}
                            {previewTab === 'plan' && sess.security_plan && (
                              <pre className="text-[12px] text-[#a1a1aa] font-mono leading-relaxed whitespace-pre-wrap">{sess.security_plan}</pre>
                            )}
                            {previewTab === 'remediation' && sess.remediation && (
                              <pre className="text-[12px] text-[#a1a1aa] font-mono leading-relaxed whitespace-pre-wrap">{sess.remediation}</pre>
                            )}
                            {previewTab === 'poc' && sess.poc && (
                              <pre className="text-[12px] text-[#a1a1aa] font-mono leading-relaxed whitespace-pre-wrap">{sess.poc}</pre>
                            )}
                            {previewTab === 'report' && sess.audit_report && (
                              <pre className="text-[12px] text-[#a1a1aa] font-mono leading-relaxed whitespace-pre-wrap">{sess.audit_report}</pre>
                            )}
                          </div>
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
              );
            })}
          </motion.div>
        )}
      </motion.div>
    </div>
  );
};
