import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { AgentHandoffPanel } from '../components/securecoder/AgentHandoffPanel';
import { downloadRunwayArtifact } from '../services/runwayArtifacts';

interface RunwaySession {
  id: number;
  product_id: number;
  product_name: string;
  status: string;
  current_step: number;
  auto_mode: boolean;
  threat_model: string | null;
  security_plan: string | null;
  remediation: string | null;
  poc: string | null;
  audit_report: string | null;
  scan_count_before: number;
  scan_count_after: number;
  error_message: string | null;
  created_at: string;
  updated_at: string;
}

type PreviewTab = 'threat' | 'plan' | 'remediation' | 'poc' | 'report';

interface RunwayReportsPageProps {
  initialSessionId?: number | null;
  onNavigateToOverview?: () => void;
}

const downloadText = (content: string, filename: string) => {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
};

const buildLegacySummary = (session: RunwaySession) => {
  let markdown = '# 🛡️ AITriage Security Audit Report\n\n';
  markdown += `**Project**: ${session.product_name || 'Unknown'}\n`;
  markdown += `**Date**: ${new Date(session.created_at).toLocaleString()}\n`;
  markdown += `**Session ID**: ${session.id}\n`;
  markdown += `**Status**: ${session.status}\n`;
  markdown += `**Findings**: ${session.scan_count_before} before → ${session.scan_count_after} after\n\n---\n\n`;

  const sections = [
    ['1. STRIDE Threat Model', session.threat_model],
    ['2. Security Implementation Plan', session.security_plan],
    ['3. Remediation Patches', session.remediation],
    ['4. Proof of Concept Verification', session.poc],
    ['5. Audit Report', session.audit_report],
  ];
  for (const [title, content] of sections) {
    if (content) markdown += `## ${title}\n\n${content}\n\n---\n\n`;
  }
  return `${markdown}\n*Generated by AITriage SecureCoder Agent*\n`;
};

export const RunwayReportsPage: React.FC<RunwayReportsPageProps> = ({ initialSessionId, onNavigateToOverview }) => {
  const { t } = useTranslation('pages');
  const [sessions, setSessions] = useState<RunwaySession[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [expandedId, setExpandedId] = useState<number | null>(null);
  const [exportingId, setExportingId] = useState<number | null>(null);
  const [previewTab, setPreviewTab] = useState<PreviewTab>('report');

  const fetchSessions = useCallback(async () => {
    setLoading(true);
    setError('');
    try {
      const response = await fetch('/api/runway/all');
      const data = await response.json();
      if (!data.ok) throw new Error(data.error || t('RunwayReportsPage.loadFailed'));
      const nextSessions: RunwaySession[] = data.sessions || [];
      setSessions(nextSessions);
      if (initialSessionId && nextSessions.some((session) => session.id === initialSessionId)) {
        setPreviewTab('report');
        setExpandedId(initialSessionId);
        window.requestAnimationFrame(() => {
          document.getElementById(`runway-report-${initialSessionId}`)?.scrollIntoView({ block: 'start' });
        });
      }
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : t('RunwayReportsPage.networkError'));
    } finally {
      setLoading(false);
    }
  }, [initialSessionId, t]);

  useEffect(() => {
    const timer = window.setTimeout(() => { void fetchSessions(); }, 0);
    return () => window.clearTimeout(timer);
  }, [fetchSessions]);

  const handleDownloadMarkdown = async (session: RunwaySession) => {
    try {
      const downloaded = await downloadRunwayArtifact(
        session.id,
        'summary_markdown',
        `runway-${session.id}-summary.md`,
      );
      if (downloaded) return;
    } catch {
      // Pre-handoff sessions use the compatibility summary below.
    }
    const date = new Date(session.created_at).toISOString().split('T')[0];
    downloadText(buildLegacySummary(session), `runway-report-${session.id}-${date}.md`);
  };

  const handleExportToProject = async (session: RunwaySession) => {
    setExportingId(session.id);
    try {
      const response = await fetch(`/api/runway/export/${session.id}`, { method: 'POST' });
      const data = await response.json();
      if (data.ok) {
        alert(t('SimpleDashboardPage.runway.exportSuccess', { path: data.saved_to || 'aitriage/' }));
      } else {
        alert(data.error || t('RunwayReportsPage.exportFailed'));
      }
    } catch {
      alert(t('RunwayReportsPage.exportNetworkError'));
    } finally {
      setExportingId(null);
    }
  };

  const counts = useMemo(() => ({
    total: sessions.length,
    completed: sessions.filter((session) => session.status === 'completed').length,
    inProgress: sessions.filter((session) => session.status === 'running' || session.status === 'in_progress').length,
    failed: sessions.filter((session) => session.status === 'failed').length,
  }), [sessions]);

  const latestCompleted = useMemo(
    () => sessions.reduce<RunwaySession | null>((latest, session) => {
      if (session.status !== 'completed') return latest;
      if (!latest) return session;
      return new Date(session.created_at).getTime() > new Date(latest.created_at).getTime() ? session : latest;
    }, null),
    [sessions],
  );

  const openSession = (sessionId: number, reveal = false) => {
    const willOpen = expandedId !== sessionId;
    setPreviewTab('report');
    setExpandedId(willOpen ? sessionId : null);
    if (willOpen && reveal) {
      window.requestAnimationFrame(() => {
        document.getElementById(`runway-report-${sessionId}`)?.scrollIntoView({ block: 'start' });
      });
    }
  };

  const statItems = [
    { label: t('RunwayReportsPage.total'), value: counts.total, icon: 'history' },
    { label: t('RunwayReportsPage.completed'), value: counts.completed, icon: 'check_circle' },
    { label: t('RunwayReportsPage.inProgress'), value: counts.inProgress, icon: 'progress_activity' },
    { label: t('RunwayReportsPage.failed'), value: counts.failed, icon: 'error' },
  ];

  return (
    <div className="h-full overflow-y-auto" style={{ scrollbarWidth: 'thin', scrollbarColor: 'rgba(255,255,255,0.08) transparent' }}>
      <div className="max-w-6xl mx-auto px-5 sm:px-8 py-7 space-y-5">
        <header className="flex flex-wrap items-start justify-between gap-4">
          <div className="max-w-2xl">
            <h1 className="text-[20px] font-bold text-[#f4f4f5] tracking-[-0.02em] flex items-center gap-2.5">
              <span className="material-symbols-outlined text-[22px] text-[var(--accent-color)]" aria-hidden="true">description</span>
              {t('RunwayReportsPage.title')}
            </h1>
            <p className="text-[13px] leading-relaxed text-[#a1a1aa] mt-1.5">
              {t('RunwayReportsPage.subtitle')}
            </p>
          </div>
          <div className="flex items-center gap-2">
            {onNavigateToOverview && (
              <button
                type="button"
                onClick={onNavigateToOverview}
                className="min-h-10 px-3.5 rounded-md bg-[var(--accent-color)] hover:bg-[var(--accent-color-hover)] text-[var(--accent-color-on-text)] text-[12px] font-semibold transition-colors flex items-center gap-1.5"
              >
                <span className="material-symbols-outlined text-[16px]" aria-hidden="true">play_arrow</span>
                {t('RunwayReportsPage.newAudit')}
              </button>
            )}
            <button
              type="button"
              onClick={() => void fetchSessions()}
              className="min-h-10 px-3.5 rounded-md border border-[rgba(255,255,255,0.09)] hover:bg-[rgba(255,255,255,0.04)] text-[12px] text-[#c4c4cc] transition-colors flex items-center gap-1.5"
            >
              <span className="material-symbols-outlined text-[16px]" aria-hidden="true">refresh</span>
              {t('RunwayReportsPage.refresh')}
            </button>
          </div>
        </header>

        {latestCompleted && (
          <section className="flex flex-wrap items-center justify-between gap-4 p-4 bg-[var(--accent-color-soft)] border border-[var(--accent-color-line)] rounded-lg">
            <div className="flex min-w-0 items-start gap-3">
              <span className="material-symbols-outlined text-[22px] text-[var(--accent-color)] mt-0.5" aria-hidden="true">verified</span>
              <div className="min-w-0">
                <h2 className="text-[15px] font-semibold text-[#f4f4f5]">{t('RunwayReportsPage.latestTitle')}</h2>
                <p className="text-[12px] leading-relaxed text-[#a1a1aa] mt-1">
                  {t('RunwayReportsPage.latestDesc', { project: latestCompleted.product_name })}
                </p>
              </div>
            </div>
            <div className="flex flex-wrap items-center gap-2">
              <button
                type="button"
                onClick={() => openSession(latestCompleted.id, true)}
                className="min-h-10 px-4 rounded-md bg-[var(--accent-color)] hover:bg-[var(--accent-color-hover)] text-[var(--accent-color-on-text)] text-[12px] font-semibold transition-colors flex items-center gap-1.5"
              >
                <span className="material-symbols-outlined text-[17px]" aria-hidden="true">visibility</span>
                {t('RunwayReportsPage.openFullReport')}
              </button>
              <button
                type="button"
                onClick={() => void handleDownloadMarkdown(latestCompleted)}
                className="min-h-10 px-4 rounded-md bg-[rgba(255,255,255,0.04)] hover:bg-[rgba(255,255,255,0.07)] border border-[rgba(255,255,255,0.09)] text-[#e4e4e7] text-[12px] font-semibold transition-colors flex items-center gap-1.5"
              >
                <span className="material-symbols-outlined text-[17px]" aria-hidden="true">download</span>
                {t('RunwayReportsPage.downloadSummary')}
              </button>
            </div>
          </section>
        )}

        <section className="grid grid-cols-2 md:grid-cols-4 bg-[rgba(255,255,255,0.015)] border border-[rgba(255,255,255,0.07)] rounded-lg overflow-hidden">
          {statItems.map((item) => (
            <div key={item.label} className="flex items-center gap-3 min-h-[70px] px-4 border-b md:border-b-0 border-r last:border-r-0 border-[rgba(255,255,255,0.06)]">
              <span className="material-symbols-outlined text-[18px] text-[#71717a]" aria-hidden="true">{item.icon}</span>
              <div>
                <div className="text-[20px] leading-none font-bold text-[#f4f4f5] tabular-nums">{item.value}</div>
                <div className="text-[11px] text-[#71717a] mt-1">{item.label}</div>
              </div>
            </div>
          ))}
        </section>

        {error && (
          <div role="alert" className="flex items-center gap-3 p-4 bg-[rgba(239,68,68,0.06)] border border-[rgba(239,68,68,0.18)] rounded-lg text-[12px] text-[#fca5a5]">
            <span className="material-symbols-outlined text-[18px]" aria-hidden="true">error</span>
            <span className="flex-1">{error}</span>
            <button type="button" onClick={() => void fetchSessions()} className="font-semibold text-[#fecaca] hover:text-white">{t('RunwayReportsPage.retry')}</button>
          </div>
        )}

        {loading ? (
          <div className="space-y-2" aria-label={t('RunwayReportsPage.loading')}>
            {[0, 1, 2].map((item) => (
              <div key={item} className="h-[78px] rounded-lg bg-[rgba(255,255,255,0.025)] animate-pulse" />
            ))}
          </div>
        ) : sessions.length === 0 ? (
          <div className="py-14 px-5 text-center border border-[rgba(255,255,255,0.07)] rounded-lg bg-[rgba(255,255,255,0.01)]">
            <span className="material-symbols-outlined text-[38px] text-[#52525b] block mb-3" aria-hidden="true">description</span>
            <h2 className="text-[15px] font-semibold text-[#e4e4e7]">{t('RunwayReportsPage.empty')}</h2>
            <p className="text-[12px] text-[#71717a] mt-1.5">{t('RunwayReportsPage.emptyDesc')}</p>
            {onNavigateToOverview && (
              <button type="button" onClick={onNavigateToOverview} className="mt-5 min-h-10 px-4 rounded-md bg-[var(--accent-color)] text-[var(--accent-color-on-text)] text-[12px] font-semibold">
                {t('RunwayReportsPage.newAudit')}
              </button>
            )}
          </div>
        ) : (
          <section className="border border-[rgba(255,255,255,0.07)] rounded-lg overflow-hidden divide-y divide-[rgba(255,255,255,0.07)] bg-[rgba(255,255,255,0.01)]">
            {sessions.map((session) => {
              const isExpanded = expandedId === session.id;
              const date = new Date(session.created_at).toLocaleDateString(undefined, {
                year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit',
              });
              const statusIcon = session.status === 'completed' ? 'check_circle' : session.status === 'failed' ? 'error' : 'progress_activity';
              const tabs: Array<{ id: PreviewTab; label: string; data: string | null }> = [
                { id: 'report', label: t('RunwayReportsPage.auditReport'), data: session.audit_report },
                { id: 'remediation', label: t('RunwayReportsPage.fixSpec'), data: session.remediation },
                { id: 'threat', label: t('RunwayReportsPage.threatModel'), data: session.threat_model },
                { id: 'plan', label: t('RunwayReportsPage.securityPlan'), data: session.security_plan },
                { id: 'poc', label: t('RunwayReportsPage.verification'), data: session.poc },
              ];
              const activeContent = tabs.find((tab) => tab.id === previewTab)?.data;

              return (
                <article key={session.id} id={`runway-report-${session.id}`}>
                  <div className="flex flex-wrap items-center gap-3 px-4 py-3.5 hover:bg-[rgba(255,255,255,0.018)] transition-colors">
                    <button
                      type="button"
                      onClick={() => openSession(session.id)}
                      aria-expanded={isExpanded}
                      className="flex flex-1 min-w-[250px] items-center gap-3 text-left"
                    >
                      <span className={`material-symbols-outlined text-[19px] ${session.status === 'completed' ? 'text-[#61b995]' : session.status === 'failed' ? 'text-[#f87171]' : 'text-[#a1a1aa]'}`} aria-hidden="true">
                        {statusIcon}
                      </span>
                      <div className="min-w-0">
                        <div className="text-[13px] font-semibold text-[#f4f4f5] truncate">
                          {session.product_name || t('RunwayReportsPage.unknownProject')}
                        </div>
                        <div className="flex flex-wrap items-center gap-x-2 gap-y-1 mt-1 text-[11px] text-[#71717a]">
                          <span>{date}</span>
                          <span>·</span>
                          <span>{t('RunwayReportsPage.session', { id: session.id })}</span>
                          <span>·</span>
                          <span>{session.status === 'completed'
                            ? t('RunwayReportsPage.findingsDelta', { before: session.scan_count_before, after: session.scan_count_after })
                            : t('RunwayReportsPage.step', { current: session.current_step })}
                          </span>
                        </div>
                      </div>
                    </button>

                    <div className="flex flex-wrap items-center gap-2">
                      <button
                        type="button"
                        onClick={() => openSession(session.id)}
                        className={`min-h-9 px-3 rounded-md text-[12px] font-semibold transition-colors flex items-center gap-1.5 ${
                          isExpanded
                            ? 'bg-[var(--accent-color-soft)] text-[var(--accent-color)]'
                            : 'bg-[var(--accent-color)] text-[var(--accent-color-on-text)] hover:bg-[var(--accent-color-hover)]'
                        }`}
                      >
                        <span className="material-symbols-outlined text-[16px]" aria-hidden="true">{isExpanded ? 'expand_less' : 'visibility'}</span>
                        {isExpanded ? t('RunwayReportsPage.closeReport') : t('RunwayReportsPage.openReport')}
                      </button>
                      <button
                        type="button"
                        onClick={() => void handleDownloadMarkdown(session)}
                        disabled={session.status !== 'completed'}
                        className="min-h-9 px-3 rounded-md border border-[rgba(255,255,255,0.09)] hover:bg-[rgba(255,255,255,0.04)] text-[#c4c4cc] text-[12px] font-medium transition-colors flex items-center gap-1.5 disabled:opacity-35"
                      >
                        <span className="material-symbols-outlined text-[16px]" aria-hidden="true">download</span>
                        {t('RunwayReportsPage.download')}
                      </button>
                      <button
                        type="button"
                        onClick={() => void handleExportToProject(session)}
                        disabled={exportingId === session.id || session.status !== 'completed'}
                        className="min-h-9 px-3 rounded-md hover:bg-[rgba(255,255,255,0.04)] text-[#a1a1aa] text-[12px] font-medium transition-colors flex items-center gap-1.5 disabled:opacity-35"
                      >
                        <span className="material-symbols-outlined text-[16px]" aria-hidden="true">drive_file_move</span>
                        {exportingId === session.id ? t('RunwayReportsPage.saving') : t('RunwayReportsPage.saveToProject')}
                      </button>
                    </div>
                  </div>

                  {isExpanded && (
                    <div className="border-t border-[rgba(255,255,255,0.07)] bg-[rgba(255,255,255,0.012)] px-4 py-4 space-y-4">
                      {session.status === 'completed' ? (
                        <AgentHandoffPanel sessionId={session.id} enabled />
                      ) : session.error_message ? (
                        <div className="p-3 rounded-md bg-[rgba(239,68,68,0.06)] text-[12px] text-[#fca5a5]">{session.error_message}</div>
                      ) : null}

                      <div role="tablist" aria-label={t('RunwayReportsPage.reportSections')} className="flex gap-1 overflow-x-auto border-b border-[rgba(255,255,255,0.07)] pb-2">
                        {tabs.map((tab) => (
                          <button
                            type="button"
                            role="tab"
                            aria-selected={previewTab === tab.id}
                            key={tab.id}
                            disabled={!tab.data}
                            onClick={() => setPreviewTab(tab.id)}
                            className={`shrink-0 min-h-9 px-3 rounded-md text-[12px] font-medium transition-colors ${
                              previewTab === tab.id
                                ? 'bg-[var(--accent-color-soft)] text-[var(--accent-color)]'
                                : tab.data
                                  ? 'text-[#a1a1aa] hover:text-[#e4e4e7] hover:bg-[rgba(255,255,255,0.03)]'
                                  : 'text-[#3f3f46] cursor-not-allowed'
                            }`}
                          >
                            {tab.label}
                          </button>
                        ))}
                      </div>

                      <div role="tabpanel" className="bg-[#0b0b0d] rounded-lg p-4 overflow-auto max-h-[480px]">
                        {activeContent ? (
                          <pre className="text-[12px] text-[#c4c4cc] font-mono leading-relaxed whitespace-pre-wrap break-words">{activeContent}</pre>
                        ) : (
                          <p className="text-[12px] text-[#71717a]">{t('RunwayReportsPage.sectionUnavailable')}</p>
                        )}
                      </div>
                    </div>
                  )}
                </article>
              );
            })}
          </section>
        )}
      </div>
    </div>
  );
};
